name: Travel Agency CI

on:
  pull_request:
    branches: [ trunk ]
  push:
    branches:
      - trunk

jobs:
  validation:
    name: Gradle Validation
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    name: Gradle Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Gradle
        run: ./gradlew clean build
