name: Travel Agency CI

on:
  pull_request:
    branches: [ trunk ]
  push:
    branches: [ trunk ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Gradle
        run: ./gradlew clean build
